---
# Copyright 2016 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Are you ppc64le ?
  fail: msg="Only ppc64le is supported. Exit."
  when: ansible_architecture != "ppc64le"

- name: OS == Ubuntu ?
  fail: msg="Only Ubuntu is supported. Exit"
  when: ansible_distribution != "Ubuntu"

- name: Deploy OpenStack basic packages for OpenPOWER
  debug: msg="Deploy OpenStack Basic Packages"

# TODO - generate hosts file
# - name: Build hosts file
#   lineinfile: dest=/etc/hosts regexp='.*{{ item }}$'
#               line='{{ hostvars[item].ansible_eth0.ipv4.address }} {{item}}'
#               state=present
#   when: hostvars[item].ansible_eth0.ipv4.address is defined
#   with_items: "{{ groups['all'] }}"

- name: Enable repository node
  template: src=sources.list
            dest=/etc/apt/sources.list
            owner=root
            group=root
            mode=0644
  when: ENABLE_REPO == True

- name: Install package for apt-add-repository
  apt: name=software-properties-common
       state=present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Add Ubuntu Cloud Archive for OpenStack Mitaka
  command: apt-add-repository -y cloud-archive:mitaka
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: Update apt repo
  apt: update_cache=yes

- name: Install packages
  apt: name={{ item }}
       state=present
  with_flattened:
    - "{{ base_packages }}"
